package com.gf.empresa.entities;
// Generated 14 ene 2026, 13:11:09 by Hibernate Tools 6.5.1.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private int emplNo;
	private Departamentos departamentos;
	private String nombre;
	private String apellidos;
	private String oficio;
	private String salario;

	public Empleados() {
	}

	public Empleados(int emplNo, Departamentos departamentos, String nombre, String apellidos, String oficio,
			String salario) {
		this.emplNo = emplNo;
		this.departamentos = departamentos;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.oficio = oficio;
		this.salario = salario;
	}

	public int getEmplNo() {
		return this.emplNo;
	}

	public void setEmplNo(int emplNo) {
		this.emplNo = emplNo;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public String getSalario() {
		return this.salario;
	}

	public void setSalario(String salario) {
		this.salario = salario;
	}

}
